export default [
  { value: "CE", type: "clear" },
  { value: "<=", type: "backspace" },
  { value: "%", type: "percentage" },
  { value: "+", type: "operator" },
  { value: "7", type: "input" },
  { value: "8", type: "input" },
  { value: "9", type: "input" },
  { value: "-", type: "operator" },
  { value: "4", type: "input" },
  { value: "5", type: "input" },
  { value: "6", type: "input" },
  { value: "*", type: "operator" },
  { value: "1", type: "input" },
  { value: "2", type: "input" },
  { value: "3", type: "input" },
  { value: "/", type: "operator" },
  { value: "0", type: "input" },
  { value: ".", type: "input" },
  { value: "=", type: "equal" },
];
